import "./globals.css";
import type { Metadata } from "next";
import Menubar from "@/components/shared/Navbar";
import SupabaseProvider from "@/providers/supabase-context";
import ScrollProvider from "@/providers/scroll-context";
import localFont from "next/font/local";
import { Providers } from "./providers";

export const revalidate = 0;

const mona = localFont({
  src: [
    {
      path: "../fonts/mona-sans/MonaSans-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../fonts/mona-sans/MonaSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/mona-sans/MonaSans-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-mona",
  display: "swap",
});
const hubot = localFont({
  src: [
    {
      path: "../fonts/hubot-sans/HubotSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/hubot-sans/HubotSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/hubot-sans/HubotSansCondensed-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-hublot",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${mona.variable} ${hubot.variable}`}>
        <Providers>
          <ScrollProvider>
            <SupabaseProvider>
              <Menubar />
              <>{children}</>
            </SupabaseProvider>
          </ScrollProvider>
        </Providers>
      </body>
    </html>
  );
}
